version: '3.8'

services:
  scram-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scram-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      - NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION}
      - NEXT_PUBLIC_BING_VERIFICATION=${NEXT_PUBLIC_BING_VERIFICATION}
      - NEXT_PUBLIC_YANDEX_VERIFICATION=${NEXT_PUBLIC_YANDEX_VERIFICATION}
      - NEXT_PUBLIC_SITE_URL=https://scram2k.com
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scram-web.rule=Host(`scram2k.com`) || Host(`www.scram2k.com`)"
      - "traefik.http.routers.scram-web.entrypoints=websecure"
      - "traefik.http.routers.scram-web.tls=true"
      - "traefik.http.routers.scram-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.scram-web.loadbalancer.server.port=3000"
      # Redirección de www a no-www
      - "traefik.http.middlewares.scram-web-redirect.redirectregex.regex=^https://www\\.scram2k\\.com/(.*)"
      - "traefik.http.middlewares.scram-web-redirect.redirectregex.replacement=https://scram2k.com/$${1}"
      - "traefik.http.middlewares.scram-web-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.scram-web.middlewares=scram-web-redirect"
      # Redirección HTTP a HTTPS
      - "traefik.http.routers.scram-web-http.rule=Host(`scram2k.com`) || Host(`www.scram2k.com`)"
      - "traefik.http.routers.scram-web-http.entrypoints=web"
      - "traefik.http.routers.scram-web-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  traefik-public:
    external: true
